damaging_moves = [
"Absorb","Accelerock","Acid","Acid Spray","Acrobatics","Aerial Ace","Aeroblast","Air Cutter","Air Slash",
"All-Out Pummeling","Anchor Shot","Ancient Power","Apple Acid","Aqua Cutter","Aqua Jet","Aqua Step","Aqua Tail",
"Arm Thrust","Aromatic Mist","Assurance","Astonish","Astral Barrage","Attack Order","Aura Sphere","Aurora Beam",
"Avalanche","Axe Kick","Baneful Bunker","Barb Barrage","Barrage","Beak Blast","Beat Up","Behemoth Bash",
"Behemoth Blade","Belch","Bide","Bind","Bite","Bitter Blade","Bitter Malice","Blast Burn","Blaze Kick",
"Blazing Torque","Bleakwind Storm","Blizzard","Body Press","Body Slam","Bolt Beak","Bolt Strike","Bone Club",
"Bone Rush","Bonemerang","Boomburst","Bounce","Branch Poke","Brave Bird","Breaking Swipe","Breakneck Blitz",
"Brick Break","Brine","Brutal Swing","Bubble","Bubble Beam","Bug Bite","Bug Buzz","Bulldoze","Bullet Punch",
"Bullet Seed","Burn Up","Burning Jealousy","Calm Mind","Catastropika","Ceaseless Edge","Chip Away","Chloroblast",
"Circle Throw","Clamp","Clanging Scales","Clear Smog","Close Combat","Collision Course","Comet Punch","Comeuppance",
"Confusion","Constrict","Continental Crush","Core Enforcer","Corkscrew Crash","Counter","Covet","Crabhammer",
"Cross Chop","Cross Poison","Crunch","Crush Claw","Crush Grip","Cut","Dark Pulse","Darkest Lariat","Dazzling Gleam",
"Diamond Storm","Dig","Dire Claw","Disarming Voice","Discharge","Dive","Dizzy Punch","Doom Desire","Double Hit",
"Double Iron Bash","Double Kick","Double Shock","Double Slap","Double-Edge","Draco Meteor","Dragon Ascent",
"Dragon Breath","Dragon Claw","Dragon Darts","Dragon Energy","Dragon Hammer","Dragon Pulse","Dragon Rage",
"Dragon Rush","Dragon Tail","Drain Punch","Draining Kiss","Dream Eater","Drill Peck","Drill Run","Drum Beating",
"Dual Chop","Dual Wingbeat","Dynamax Cannon","Dynamic Punch","Earth Power","Earthquake","Echoed Voice",
"Eerie Spell","Egg Bomb","Electro Ball","Electro Drift","Electroweb","Ember","Endeavor","Energy Ball","Eruption",
"Esper Wing","Eternabeam","Expanding Force","Explosion","Extrasensory","Extreme Speed","Facade","Fairy Wind",
"Fake Out","False Surrender","False Swipe","Feint","Feint Attack","Fell Stinger","Fiery Dance","Fiery Wrath",
"Final Gambit","Fire Blast","Fire Fang","Fire Lash","Fire Pledge","Fire Punch","Fire Spin","First Impression",
"Fishious Rend","Fissure","Flail","Flame Burst","Flame Charge","Flame Wheel","Flamethrower","Flare Blitz",
"Flash Cannon","Fleur Cannon","Fling","Flip Turn","Floaty Fall","Fly","Flying Press","Focus Blast","Focus Punch",
"Force Palm","Foul Play","Freeze-Dry","Freeze Shock","Freezing Glare","Frenzy Plant","Frost Breath","Frustration",
"Fury Attack","Fury Cutter","Fury Swipes","Fusion Bolt","Fusion Flare","Future Sight","G-Max Cannonade",
"G-Max Centiferno","G-Max Chi Strike","G-Max Cuddle","G-Max Depletion","G-Max Drum Solo","G-Max Finale",
"G-Max Fireball","G-Max Foam Burst","G-Max Gold Rush","G-Max Gravitas","G-Max Hydrosnipe","G-Max Malodor",
"G-Max Meltdown","G-Max One Blow","G-Max Rapid Flow","G-Max Replenish","G-Max Resonance","G-Max Sandblast",
"G-Max Smite","G-Max Snooze","G-Max Steelsurge","G-Max Stonesurge","G-Max Stun Shock","G-Max Sweetness",
"G-Max Tartness","G-Max Terror","G-Max Vine Lash","G-Max Volcalith","G-Max Wildfire","Gear Grind","Genesis Supernova",
"Giga Drain","Giga Impact","Gigaton Hammer","Gigavolt Havoc","Glacial Lance","Glaciate","Glaive Rush","Glare",
"Grass Knot","Grass Pledge","Grav Apple","Gravity","Growl","Guard Split","Guardian of Alola","Guillotine",
"Gunk Shot","Gust","Gyro Ball","Hammer Arm","Head Charge","Head Smash","Headbutt","Heat Crash","Heat Wave",
"Heavy Slam","Hex","High Horsepower","High Jump Kick","Horn Attack","Horn Drill","Horn Leech","Hurricane",
"Hydro Cannon","Hydro Pump","Hydro Steam","Hyper Beam","Hyper Drill","Hyper Fang","Hyper Voice","Hyperspace Fury",
"Hyperspace Hole","Ice Beam","Ice Fang","Ice Hammer","Ice Punch","Ice Shard","Ice Spinner","Icicle Crash",
"Icicle Spear","Icy Wind","Incinerate","Infernal Parade","Inferno","Infestation","Iron Head","Iron Tail",
"Ivy Cudgel","Jet Punch","Judgment","Jump Kick","Karate Chop","Knock Off","Kowtow Cleave","Land's Wrath",
"Lash Out","Last Resort","Last Respects","Lava Plume","Leaf Blade","Leaf Storm","Leaf Tornado","Leafage",
"Leech Life","Lick","Liquidation","Low Kick","Low Sweep","Lunge","Luster Purge","Mach Punch","Magical Torque",
"Magma Storm","Magnet Bomb","Magnitude","Make It Rain","Malicious Moonsault","Mean Look","Mega Drain","Mega Kick",
"Mega Punch","Megahorn","Meteor Assault","Meteor Beam","Meteor Mash","Mind Blown","Mirror Shot","Mist Ball",
"Misty Explosion","Moonblast","Moongeist Beam","Mortal Spin","Mountain Gale","Mud Bomb","Mud Shot","Mud-Slap",
"Muddy Water","Multi-Attack","Mystical Fire","Nasty Plot","Natural Gift","Night Daze","Night Shade","Night Slash",
"Nuzzle","Oblivion Wing","Oceanic Operetta","Octazooka","Ominous Wind","Order Up","Origin Pulse","Outrage",
"Overdrive","Overheat","Pain Split","Parabolic Charge","Pay Day","Payback","Peck","Petal Blizzard","Petal Dance",
"Phantom Force","Photon Geyser","Pin Missile","Plasma Fists","Play Rough","Pluck","Poison Fang","Poison Jab",
"Poison Sting","Poison Tail","Pollen Puff","Pound","Powder Snow","Power Gem","Power Trip","Power Whip",
"Power-Up Punch","Precipice Blades","Psybeam","Psychic","Psychic Fangs","Psycho Boost","Psycho Cut","Psyshock",
"Pyro Ball","Quick Attack","Rage","Raging Bull","Raging Fury","Razor Leaf","Razor Shell","Razor Wind","Recover",
"Relic Song","Retaliate","Return","Revelation Dance","Revenge","Reversal","Rising Voltage","Roar of Time",
"Rock Blast","Rock Climb","Rock Slide","Rock Smash","Rock Throw","Rock Tomb","Rock Wrecker","Rolling Kick",
"Rollout","Roost","Round","Sacred Fire","Sacred Sword","Sand Tomb","Sandsear Storm","Scald","Scale Shot",
"Scorching Sands","Scratch","Searing Shot","Searing Sunraze Smash","Secret Power","Seed Bomb","Seed Flare",
"Seismic Toss","Self-Destruct","Shadow Ball","Shadow Bone","Shadow Claw","Shadow Force","Shadow Punch",
"Shadow Sneak","Sharpen","Sheer Cold","Shell Side Arm","Shell Trap","Shock Wave","Signal Beam","Silver Wind",
"Sinister Arrow Raid","Sizzly Slide","Skitter Smack","Skull Bash","Sky Attack","Sky Drop","Sky Uppercut",
"Slam","Slash","Sleep Talk","Sludge","Sludge Bomb","Sludge Wave","Smack Down","Smart Strike","Smelling Salts",
"Smog","Snarl","Snipe Shot","Snore","Solar Beam","Solar Blade","Soul-Stealing 7-Star Strike","Spark","Sparkling Aria",
"Spectral Thief","Speed Swap","Spike Cannon","Spirit Break","Spirit Shackle","Spit Up","Spit Up","Spore",
"Steam Eruption","Steamroller","Steel Beam","Steel Roller","Steel Wing","Stomp","Stomping Tantrum","Stone Axe",
"Stone Edge","Stored Power","Storm Throw","Strange Steam","Strength","Struggle","Struggle Bug","Submission",
"Subzero Slammer","Sucker Punch","Sunsteel Strike","Super Fang","Superpower","Supersonic Skystrike","Surf",
"Swift","Tackle","Tail Slap","Take Down","Tar Shot","Tearful Look","Teatime","Techno Blast","Temper Flare",
"Thief","Thrash","Throat Chop","Thunder","Thunder Fang","Thunder Punch","Thunder Shock","Thunderbolt",
"Thunderous Kick","Tidal Storm","Tidy Up","Topsy-Turvy","Torch Song","Toxic Thread","Trailblaze","Tri Attack",
"Triple Arrows","Triple Axel","Triple Kick","Trop Kick","Trump Card","Twin Beam","Twineedle","U-turn",
"Upper Hand","Vacuum Wave","V-create","Veevee Volley","Venoshock","Vine Whip","Vise Grip","Vital Throw",
"Volt Switch","Volt Tackle","Wake-Up Slap","Water Gun","Water Pledge","Water Pulse","Water Shuriken",
"Waterfall","Wave Crash","Weather Ball","Whirlpool","Wild Charge","Wildbolt Storm","Wing Attack","Wood Hammer",
"Wicked Blow","Wicked Torque","X-Scissor","Yawn","Zap Cannon","Zen Headbutt","Zing Zap"
]

all_moves = [
"Absorb","Accelerock","Acid","Acid Armor","Acid Spray","Acrobatics","Acupressure","Aerial Ace","Aeroblast",
"After You","Agility","Air Cutter","Air Slash","All-Out Pummeling","Ally Switch","Amnesia","Anchor Shot",
"Ancient Power","Apple Acid","Aqua Cutter","Aqua Jet","Aqua Ring","Aqua Step","Aqua Tail","Arm Thrust",
"Armor Cannon","Aromatherapy","Aromatic Mist","Assist","Assurance","Astonish","Astral Barrage","Attack Order",
"Attract","Aura Sphere","Aurora Beam","Aurora Veil","Autotomize","Avalanche","Axe Kick","Baby-Doll Eyes",
"Baneful Bunker","Barb Barrage","Barrage","Barrier","Baton Pass","Beak Blast","Beat Up","Behemoth Bash",
"Behemoth Blade","Belch","Belly Drum","Bestow","Bide","Bind","Bite","Bitter Blade","Bitter Malice",
"Black Hole Eclipse","Blast Burn","Blaze Kick","Blazing Torque","Bleakwind Storm","Blizzard","Block",
"Bloom Doom","Blue Flare","Body Press","Body Slam","Bolt Beak","Bolt Strike","Bone Club","Bone Rush",
"Bonemerang","Boomburst","Bounce","Bouncy Bubble","Branch Poke","Brave Bird","Breaking Swipe","Breakneck Blitz",
"Brick Break","Brine","Brutal Swing","Bubble","Bubble Beam","Bug Bite","Bug Buzz","Bulk Up","Bulldoze",
"Bullet Punch","Bullet Seed","Burn Up","Burning Jealousy","Buzzy Buzz","Calm Mind","Camouflage","Captivate",
"Catastropika","Ceaseless Edge","Celebrate","Charge","Charge Beam","Charm","Chatter","Chilling Water",
"Chilly Reception","Chip Away","Chloroblast","Circle Throw","Clamp","Clanging Scales","Clangorous Soul",
"Clangorous Soulblaze","Clear Smog","Close Combat","Coaching","Coil","Collision Course","Comet Punch",
"Comeuppance","Confide","Confuse Ray","Confusion","Constrict","Continental Crush","Conversion","Conversion 2",
"Copycat","Core Enforcer","Corkscrew Crash","Corrosive Gas","Cosmic Power","Cotton Guard","Cotton Spore",
"Counter","Court Change","Covet","Crabhammer","Crafty Shield","Cross Chop","Cross Poison","Crunch","Crush Claw",
"Crush Grip","Curse","Cut","Dark Pulse","Dark Void","Darkest Lariat","Dazzling Gleam","Decorate","Defend Order",
"Defense Curl","Defog","Destiny Bond","Detect","Devastating Drake","Diamond Storm","Dig","Dire Claw","Disable",
"Disarming Voice","Discharge","Dive","Dizzy Punch","Doodle","Doom Desire","Double Hit","Double Iron Bash",
"Double Kick","Double Shock","Double Team","Double-Edge","Draco Meteor","Dragon Ascent","Dragon Breath",
"Dragon Claw","Dragon Dance","Dragon Darts","Dragon Energy","Dragon Hammer","Dragon Pulse","Dragon Rage",
"Dragon Rush","Dragon Tail","Drain Punch","Draining Kiss","Dream Eater","Drill Peck","Drill Run","Drum Beating",
"Dual Chop","Dual Wingbeat","Dynamax Cannon","Dynamic Punch","Earth Power","Earthquake","Echoed Voice",
"Eerie Impulse","Eerie Spell","Egg Bomb","Electric Terrain","Electrify","Electro Ball","Electro Drift",
"Electroweb","Embargo","Ember","Encore","Endeavor","Endure","Energy Ball","Entrainment","Eruption","Esper Wing",
"Eternabeam","Expanding Force","Explosion","Extrasensory","Extreme Evoboost","Extreme Speed","Facade",
"Fairy Lock","Fairy Wind","Fake Out","Fake Tears","False Surrender","False Swipe","Feather Dance","Feint",
"Feint Attack","Fell Stinger","Fiery Dance","Fiery Wrath","Final Gambit","Fire Blast","Fire Fang","Fire Lash",
"Fire Pledge","Fire Punch","Fire Spin","First Impression","Fishious Rend","Fissure","Flail","Flame Burst",
"Flame Charge","Flame Wheel","Flamethrower","Flare Blitz","Flash","Flash Cannon","Flatter","Fleur Cannon",
"Fling","Flip Turn","Floaty Fall","Floral Healing","Flower Shield","Fly","Flying Press","Focus Blast",
"Focus Energy","Focus Punch","Follow Me","Force Palm","Foresight","Forest's Curse","Foul Play","Freeze-Dry",
"Freeze Shock","Freezing Glare","Freezy Frost","Frenzy Plant","Frost Breath","Frustration","Fury Attack",
"Fury Cutter","Fury Swipes","Fusion Bolt","Fusion Flare","Future Sight","G-Max Befuddle","G-Max Cannonade",
"G-Max Centiferno","G-Max Chi Strike","G-Max Cuddle","G-Max Depletion","G-Max Drum Solo","G-Max Finale",
"G-Max Fireball","G-Max Foam Burst","G-Max Gold Rush","G-Max Gravitas","G-Max Hydrosnipe","G-Max Malodor",
"G-Max Meltdown","G-Max One Blow","G-Max Rapid Flow","G-Max Replenish","G-Max Resonance","G-Max Sandblast",
"G-Max Smite","G-Max Snooze","G-Max Steelsurge","G-Max Stonesurge","G-Max Stun Shock","G-Max Sweetness",
"G-Max Tartness","G-Max Terror","G-Max Vine Lash","G-Max Volcalith","G-Max Wildfire","Gastro Acid","Gear Grind",
"Gear Up","Genesis Supernova","Geomancy","Giga Drain","Giga Impact","Gigaton Hammer","Gigavolt Havoc",
"Glacial Lance","Glaciate","Glaive Rush","Glare","Glitzy Glow","Grass Knot","Grass Pledge","Grass Whistle",
"Grassy Glide","Grassy Terrain","Grav Apple","Gravity","Growl","Growth","Grudge","Guard Split","Guard Swap",
"Guardian of Alola","Guillotine","Gunk Shot","Gust","Gyro Ball","Hammer Arm","Happy Hour","Harden","Haze",
"Head Charge","Head Smash","Headbutt","Heal Bell","Heal Block","Heal Order","Heal Pulse","Healing Wish",
"Heart Stamp","Heart Swap","Heat Crash","Heat Wave","Heavy Slam","Helping Hand","Hex","Hidden Power",
"High Horsepower","High Jump Kick","Hold Back","Hold Hands","Hone Claws","Horn Attack","Horn Drill",
"Horn Leech","Howl","Hurricane","Hydro Cannon","Hydro Pump","Hydro Steam","Hyper Beam","Hyper Drill",
"Hyper Fang","Hyper Voice","Hyperspace Fury","Hyperspace Hole","Hypnosis","Ice Beam","Ice Burn","Ice Fang",
"Ice Hammer","Ice Punch","Ice Shard","Ice Spinner","Icicle Crash","Icicle Spear","Icy Wind","Imprison",
"Incinerate","Infernal Parade","Inferno","Infestation","Ingrain","Instruct","Ion Deluge","Iron Defense",
"Iron Head","Iron Tail","Ivy Cudgel","Jaw Lock","Jet Punch","Judgment","Jump Kick","Jungle Healing",
"Karate Chop","Kinesis","King's Shield","Knock Off","Kowtow Cleave","Land's Wrath","Laser Focus","Lash Out",
"Last Resort","Last Respects","Lava Plume","Leaf Blade","Leaf Storm","Leaf Tornado","Leafage","Leech Life",
"Leech Seed","Leer","Let's Snuggle Forever","Lick","Life Dew","Light of Ruin","Light Screen","Liquidation",
"Lock-On","Lovely Kiss","Low Kick","Low Sweep","Lucky Chant","Lunar Blessing","Lunar Dance","Lunge",
"Luster Purge","Mach Punch","Magic Coat","Magic Powder","Magic Room","Magical Leaf","Magical Torque",
"Magma Storm","Magnet Bomb","Magnet Rise","Magnetic Flux","Magnitude","Make It Rain","Malicious Moonsault",
"Mat Block","Me First","Mean Look","Meditate","Mega Drain","Mega Kick","Mega Punch","Megahorn","Memento",
"Menacing Moonraze Maelstrom","Metal Burst","Metal Claw","Metal Sound","Meteor Assault","Meteor Beam",
"Meteor Mash","Metronome","Milk Drink","Mimic","Mind Blown","Mind Reader","Minimize","Miracle Eye",
"Mirror Coat","Mirror Move","Mirror Shot","Mist","Mist Ball","Misty Explosion","Misty Terrain","Moonblast",
"Moongeist Beam","Moonlight","Morning Sun","Mortal Spin","Mountain Gale","Mud Bomb","Mud Shot","Mud-Slap",
"Muddy Water","Multi-Attack","Mystical Fire","Nasty Plot","Natural Gift","Night Daze","Night Shade",
"Night Slash","Nightmare","Noble Roar","Noxious Torque","Nuzzle","Oblivion Wing","Oceanic Operetta",
"Octazooka","Octolock","Odor Sleuth","Ominous Wind","Order Up","Origin Pulse","Outrage","Overdrive",
"Overheat","Pain Split","Parabolic Charge","Parting Shot","Pay Day","Payback","Peck","Perish Song",
"Petal Blizzard","Petal Dance","Phantom Force","Photon Geyser","Pin Missile","Plasma Fists","Play Nice",
"Play Rough","Pluck","Poison Fang","Poison Gas","Poison Jab","Poison Powder","Poison Sting","Poison Tail",
"Pollen Puff","Pound","Powder","Powder Snow","Power Gem","Power Shift","Power Split","Power Swap",
"Power Trick","Power Trip","Power Whip","Power-Up Punch","Precipice Blades","Present","Protect","Psybeam",
"Psych Up","Psychic","Psychic Fangs","Psychic Terrain","Psycho Boost","Psycho Cut","Psyshield Bash",
"Psyshock","Psystrike","Pursuit","Pyro Ball","Quick Attack","Quick Guard","Quiver Dance","Rage",
"Rage Powder","Raging Bull","Raging Fury","Rain Dance","Rapid Spin","Razor Leaf","Razor Shell","Razor Wind",
"Recover","Recycle","Reflect","Reflect Type","Refresh","Relic Song","Rest","Retaliate","Return",
"Revelation Dance","Revenge","Reversal","Rising Voltage","Roar","Roar of Time","Rock Blast","Rock Climb",
"Rock Polish","Rock Slide","Rock Smash","Rock Throw","Rock Tomb","Rock Wrecker","Role Play","Rolling Kick",
"Rollout","Roost","Rototiller","Round","Sacred Fire","Sacred Sword","Safeguard","Sand Attack","Sand Tomb",
"Sandsear Storm","Sandstorm","Scald","Scale Shot","Scary Face","Scratch","Screech","Searing Shot",
"Searing Sunraze Smash","Secret Power","Secret Sword","Seed Bomb","Seed Flare","Seismic Toss",
"Self-Destruct","Shadow Ball","Shadow Bone","Shadow Claw","Shadow Force","Shadow Punch","Shadow Sneak",
"Sharpen","Sheer Cold","Shell Side Arm","Shell Smash","Shell Trap","Shift Gear","Shock Wave","Shore Up",
"Signal Beam","Silver Wind","Simple Beam","Sing","Sinister Arrow Raid","Sizzly Slide","Sketch","Skill Swap",
"Skitter Smack","Skull Bash","Sky Attack","Sky Drop","Sky Uppercut","Slack Off","Slam","Slash","Sleep Powder",
"Sleep Talk","Sludge","Sludge Bomb","Sludge Wave","Smack Down","Smart Strike","Smelling Salts","Smog",
"Smokescreen","Snap Trap","Snarl","Snipe Shot","Snore","Soak","Soft-Boiled","Solar Beam","Solar Blade",
"Solar Blade","Soul-Stealing 7-Star Strike","Spark","Sparkling Aria","Spectral Thief","Speed Swap",
"Spike Cannon","Spikes","Spiky Shield","Spirit Break","Spirit Shackle","Spit Up","Spite","Splash","Splintered Stormshards",
"Spore","Spotlight","Stealth Rock","Steam Eruption","Steamroller","Steel Beam","Steel Roller","Steel Wing",
"Sticky Web","Stockpile","Stomp","Stomping Tantrum","Stone Axe","Stone Edge","Stored Power","Storm Throw",
"Strange Steam","Strength","Strength Sap","String Shot","Struggle","Struggle Bug","Stuff Cheeks","Stun Spore",
"Submission","Substitute","Subzero Slammer","Sucker Punch","Sunny Day","Sunsteel Strike","Super Fang",
"Superpower","Supersonic","Supersonic Skystrike","Surf","Swagger","Swallow","Sweet Kiss","Sweet Scent",
"Swift","Switcheroo","Swords Dance","Synthesis","Tackle","Tail Glow","Tail Slap","Tail Whip","Tailwind",
"Take Down","Tar Shot","Taunt","Tearful Look","Teatime","Techno Blast","Teleport","Temper Flare","Thief",
"Thrash","Throat Chop","Thunder","Thunder Fang","Thunder Punch","Thunder Shock","Thunder Wave","Thunderbolt",
"Thunderous Kick","Tickle","Tidy Up","Topsy-Turvy","Torch Song","Torment","Toxic","Toxic Spikes","Toxic Thread",
"Trailblaze","Transform","Tri Attack","Trick","Trick Room","Triple Arrows","Triple Axel","Triple Kick",
"Trop Kick","Trump Card","Twin Beam","Twineedle","Twister","U-turn","Uproar","Vacuum Wave","V-create",
"Veevee Volley","Venom Drench","Venoshock","Vine Whip","Vise Grip","Vital Throw","Volt Switch","Volt Tackle",
"Wake-Up Slap","Water Gun","Water Pledge","Water Pulse","Water Shuriken","Water Sport","Waterfall","Wave Crash",
"Weather Ball","Whirlpool","Whirlwind","Wild Charge","Wildbolt Storm","Will-O-Wisp","Wing Attack","Wish",
"Withdraw","Wonder Room","Wood Hammer","Work Up","Worry Seed","Wrap","Wring Out","X-Scissor","Yawn",
"Zap Cannon","Zen Headbutt","Zing Zap","Zippy Zap"
]

non_damaging_moves = [
    "Acid Armor", "Acupressure", "After You", "Agility", "Amnesia", "Aqua Ring",
    "Aromatic Mist", "Assist", "Attract", "Aurora Veil", "Autotomize",
    "Baby-Doll Eyes", "Baneful Bunker", "Barrier", "Baton Pass", "Belly Drum",
    "Bestow", "Block", "Calm Mind", "Camouflage", "Captivate", "Celebrate",
    "Charm", "Chilly Reception", "Clangorous Soul", "Coaching", "Confide",
    "Confuse Ray", "Conversion", "Conversion 2", "Copycat", "Cotton Guard",
    "Cotton Spore", "Court Change", "Crafty Shield", "Curse", "Dark Void",
    "Decorate", "Defend Order", "Defense Curl", "Defog", "Destiny Bond",
    "Detect", "Disable", "Double Team", "Dragon Dance", "Eerie Impulse",
    "Electric Terrain", "Embargo", "Encore", "Endure", "Entrainment",
    "Feather Dance", "Flash", "Flatter", "Floral Healing", "Flower Shield",
    "Focus Energy", "Follow Me", "Forest’s Curse", "Foresight", "Gastro Acid",
    "Geomancy", "Glare", "Grassy Terrain", "Growl", "Growth", "Guard Split",
    "Guard Swap", "Hail", "Harden", "Haze", "Heal Bell", "Heal Block",
    "Heal Order", "Healing Wish", "Heart Swap", "Helping Hand", "Hold Hands",
    "Hone Claws", "Howl", "Hypnosis", "Imprison", "Ingrain", "Instruct",
    "Ion Deluge", "Iron Defense", "Jungle Healing", "King’s Shield",
    "Laser Focus", "Leech Seed", "Leer", "Life Dew", "Light Screen",
    "Lock-On", "Lovely Kiss", "Lucky Chant", "Lunar Dance", "Magic Coat",
    "Magic Powder", "Magic Room", "Magnet Rise", "Meditate", "Me First",
    "Metronome", "Milk Drink", "Mimic", "Mind Reader", "Minimize",
    "Miracle Eye", "Mist", "Moonlight", "Morning Sun", "Mud Sport",
    "Nasty Plot", "Nature Power", "Nightmare", "No Retreat", "Noble Roar",
    "Odor Sleuth", "Pain Split", "Parting Shot", "Perish Song", "Play Nice",
    "Poison Gas", "Poison Powder", "Powder", "Power Split", "Power Swap",
    "Power Trick", "Protect", "Psych Up", "Psychic Terrain", "Purify",
    "Quash", "Quick Guard", "Rage Powder", "Rain Dance", "Recover",
    "Recycle", "Reflect", "Refresh", "Rest", "Roar", "Rock Polish",
    "Role Play", "Roost", "Safeguard", "Sand Attack", "Sandstorm",
    "Scary Face", "Screech", "Sharpen", "Shell Smash", "Shift Gear",
    "Shore Up", "Sing", "Sketch", "Skill Swap", "Slack Off", "Sleep Powder",
    "Sleep Talk", "Smokescreen", "Soft-Boiled", "Spikes", "Spider Web",
    "Spiky Shield", "Splash", "Spore", "Stealth Rock", "Sticky Web",
    "Stockpile", "String Shot", "Stun Spore", "Substitute", "Sunny Day",
    "Supersonic", "Swagger", "Sweet Kiss", "Sweet Scent", "Switcheroo",
    "Swords Dance", "Tail Glow", "Tail Whip", "Tailwind", "Taunt",
    "Tearful Look", "Teatime", "Teleport", "Topsy-Turvy", "Torment",
    "Toxic", "Toxic Spikes", "Transform", "Trick", "Trick Room",
    "Toxic Thread", "Venom Drench", "Water Sport", "Whirlwind",
    "Wide Guard", "Will-O-Wisp", "Wish", "Withdraw", "Wonder Room",
    "Work Up", "Yawn"
]
